variables:
  SECURE_LOG_LEVEL: Debug
  VERSION: 1.0.${CI_PIPELINE_ID}

cache: 
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
  - module-pipelines
  - deploy
  - notify

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend

backend-report:
  stage: module-pipelines
  trigger:
    include:
      - "/backend-report/.gitlab-ci.yml"
    strategy: depend

deploy:
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS1" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script: 
    - echo "deploy off"
      
notify:
  stage: notify
  script:
    - echo "Send notify slack"
    - >
      curl -X POST -H 'Content-type: application/json' --data '{"text":"Вышла новая версия сосисочной — sausage-store-'${VERSION}'. http://nikolai-babentsov-0.0.k8s.praktikum-services.tech/"}' https://hooks.slack.com/services/***

