variables:
  SECURE_LOG_LEVEL: Debug
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ./.m2/repository
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

include:
  - template: Security/SAST.gitlab-ci.yml
  
cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
  - build
  - test
  - release

services:
  - docker:dind
  
build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "backend"
      --build-arg VERSION=${VERSION}
      --cache-repo ${CONTAINER_BACKEND}:latest
      --dockerfile "Dockerfile"
      "${KANIKOPROXYBUILDARGS}"
      --destination "${CONTAINER_BACKEND}:rc1"

sast:
  stage: test

nodejs-scan-sast:
  rules:
    - when: never

sonar-check:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${SONAR_HOME}"
    SONAR_HOST_URL: "${SONAR_URL}"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - cd backend
    - mvn -e verify sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectName=00_NBABENTSOV_BACK -Dsonar.projectKey=00_NBABENTSOV_BACK -Dsonar.login="${TOKEN_BACK}"
  allow_failure: true

spotbugs-sast:
  variables:
    MAVEN_REPO_PATH: .
    COMPILE: "false"
  artifacts:
    reports:
      sast: gl-sast-report.json 
 
release-docker:
  stage: release
  image: docker:20-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
  variables:
    GIT_DEPTH: "0"
    GIT_STRATEGY: none
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull ${CONTAINER_BACKEND}:rc1
    - docker tag ${CONTAINER_BACKEND}:rc1 ${CONTAINER_BACKEND}:latest
    - docker push ${CONTAINER_BACKEND}:latest

lint-dockerfile:
  stage: test
  image: docker:20-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
  script:
    - cd backend
    - docker run --rm -v $PWD:/root/ projectatomic/dockerfile-lint dockerfile_lint
    
